### Fetch all tasks
GET http://localhost:8000/tasks
Content-Type: "application/json"

### Create a new task
POST http://localhost:8000/tasks
Content-Type: "application/json"

{
  "title": "this is title 2",
  "date": "22-02-22",
  "description": "this is description",
  "priority" : "high",
  "status" : "todo"
}

### Update a task
PUT http://localhost:8000/tasks
Content-Type: "application/json"

{
  "id": "d78e7dd2-2f5f-42fd-bb62-58c2c1b95ba4",
  "status": "inProgress"
}